# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 个人博客
email: peiheyuan@agicmicro.com
description: >- # this means to ignore newlines until "baseurl:"
  本科就读于合肥工业大学计算机科学与技术专业，硕士就读于中国科学院大学人工智能专业，现为北京谦合益邦云信息技术有限公司的算法优化工程师。
github_username: peiheyuan
minimal_mistakes_skin: contrast
search: true
# logo: "/assets/images/bio-photo.jpg"
enable_copy_code_button: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Heyuan Pei"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "你看那通天的巨塔，每时每刻都有雪花落下。"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://peiheyuan.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peiheyuan"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peiheyuan"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 200
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

header:
  teaser: /assets/images/bio-photo.jpg  # for example
